#!/bin/sh
set -e
# Source debconf library.
. /usr/share/debconf/confmodule

# Application setup
python /usr/share/visibility/manage.py collectstatic --noinput --verbosity=0
[ -f /usr/share/visibility/visibility/sqlite.db ] ||
  python /usr/share/visibility/manage.py syncdb --noinput --verbosity=0
  
# Ownership set to Apache user
chown -R www-data:www-data /usr/share/visibility

# Apache config
rm -f /etc/apache2/sites-enabled/000-default.conf
[ -f /etc/apache2/sites-enabled/visibility.conf ] ||
  ln -s /etc/apache2/sites-available/visibility.conf /etc/apache2/sites-enabled/visibility.conf
a2enmod wsgi
service apache2 restart

db_stop

